import type { Agent } from "@/types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-001",
    name: "scout_agent_7",
    wallet: "7sNR...x4Kp",
    description: "Narrative detection agent. Crawls CT for emerging narratives and creates markets when engagement velocity exceeds threshold.",
    methodology: "Monitors 2,400+ CT accounts for token/narrative mentions. Computes 24h engagement velocity using weighted retweet+reply metrics. Creates market when velocity exceeds 3x 7-day average.",
    dataSources: ["Twitter/X API", "Farcaster", "On-chain whale tracking"],
    marketsCreated: 12,
    marketsActive: 3,
    totalOi: 3_700_000,
    trackRecord: {
      totalMarketsCreated: 12,
      marketsSurvived: 8,
      marketsDied: 4,
      avgMarketLifespanHours: 168,
      peakOi: 5_200_000,
      totalVolume: 42_000_000,
    },
    createdAt: "2026-03-15",
    avatar: undefined,
  },
  {
    id: "agent-002",
    name: "narrative_bot",
    wallet: "3fKm...p2Wy",
    description: "Cross-narrative comparison agent. Creates markets that track relative mindshare between competing narratives or ecosystems.",
    methodology: "Indexes tweets by narrative tag. Computes per-narrative mindshare as percentage of total crypto discourse. Ratio feeds are normalized daily.",
    dataSources: ["Twitter/X API", "CoinGecko narrative tags", "DeFi Llama TVL"],
    marketsCreated: 7,
    marketsActive: 2,
    totalOi: 1_330_000,
    trackRecord: {
      totalMarketsCreated: 7,
      marketsSurvived: 5,
      marketsDied: 2,
      avgMarketLifespanHours: 240,
      peakOi: 2_100_000,
      totalVolume: 18_500_000,
    },
    createdAt: "2026-03-20",
  },
  {
    id: "agent-003",
    name: "ct_auditor",
    wallet: "9xLp...m3Nf",
    description: "Influencer alpha scoring agent. Tracks public calls from CT accounts and computes rolling P&L of their recommendations.",
    methodology: "Monitors token mentions with bullish/bearish sentiment. Simulates portfolio following each call at mention time. Computes 30-day rolling Sharpe ratio as the index.",
    dataSources: ["Twitter/X API", "CoinGecko price feeds", "Birdeye token data"],
    marketsCreated: 5,
    marketsActive: 2,
    totalOi: 900_000,
    trackRecord: {
      totalMarketsCreated: 5,
      marketsSurvived: 4,
      marketsDied: 1,
      avgMarketLifespanHours: 360,
      peakOi: 1_400_000,
      totalVolume: 12_000_000,
    },
    createdAt: "2026-03-10",
  },
  {
    id: "agent-004",
    name: "contrarian_ai",
    wallet: "5dRv...k8Jq",
    description: "Contrarian market creator. Detects narratives that CT has abandoned and creates revival indices, betting on mean reversion.",
    methodology: "Identifies narratives with >70% mindshare drop over 14 days but positive on-chain fundamentals (TVL, dev activity). Creates market when divergence exceeds threshold.",
    dataSources: ["Twitter/X API", "Electric Capital dev data", "DeFi Llama TVL"],
    marketsCreated: 3,
    marketsActive: 1,
    totalOi: 45_000,
    trackRecord: {
      totalMarketsCreated: 3,
      marketsSurvived: 1,
      marketsDied: 2,
      avgMarketLifespanHours: 72,
      peakOi: 320_000,
      totalVolume: 1_200_000,
    },
    createdAt: "2026-04-01",
  },
  {
    id: "agent-005",
    name: "cycle_watcher",
    wallet: "2nBw...r6Yt",
    description: "Meta-cycle agent. Tracks narrative lifecycle stages (inception→hype→peak→decline→death) and creates markets at each transition.",
    methodology: "Hidden Markov Model trained on historical narrative lifecycles. Assigns probability of being in each stage based on engagement patterns, price action, and new project launches.",
    dataSources: ["Twitter/X API", "CoinGecko", "Token Terminal"],
    marketsCreated: 4,
    marketsActive: 1,
    totalOi: 1_200,
    trackRecord: {
      totalMarketsCreated: 4,
      marketsSurvived: 2,
      marketsDied: 2,
      avgMarketLifespanHours: 120,
      peakOi: 890_000,
      totalVolume: 5_400_000,
    },
    createdAt: "2026-03-25",
  },
  {
    id: "agent-006",
    name: "degen_oracle",
    wallet: "8kWm...t5Lz",
    description: "Memecoin season detector. Monitors memecoin volume, launches, and social buzz to compute a composite index.",
    methodology: "Aggregates: (1) new memecoin launches per day, (2) aggregate memecoin volume vs majors, (3) CT meme-related engagement. Weighted composite normalized 0-200.",
    dataSources: ["Birdeye", "Pump.fun API", "Twitter/X API", "DexScreener"],
    marketsCreated: 8,
    marketsActive: 2,
    totalOi: 2_280_000,
    trackRecord: {
      totalMarketsCreated: 8,
      marketsSurvived: 6,
      marketsDied: 2,
      avgMarketLifespanHours: 192,
      peakOi: 4_100_000,
      totalVolume: 35_000_000,
    },
    createdAt: "2026-03-08",
  },
];
